### ISSUE TITLE
Make sure the biosample accessions are valid

### ISSUE THREAD

**Issue by DCGenomics** [NCBI-Hackathons/Metadata_categorization#21]

**Comment by eweitz** [comment]
Fixed.

Some BioSample links were broken because [I mistakenly assumed that BioSample accession could be deduced given only BioSample ID](https://github.com/NCBI-Hackathons/Metadata_categorization/commit/247517e69d6d884ba5d89aa989b13505cec694e2).  Many can, but not all, because BioSample accessions are not all "SAMN" + 8 digits.  Examples include SAMEA3446353, which has ID 4199272.  The data in Solr contains BioSample ID but not accession.  

The simple solution is to hyperlink by BioSample ID, e.g. https://www.ncbi.nlm.nih.gov/biosample/4199272.
