### ISSUE TITLE
Populate sample name and sample title fields in UI

### ISSUE THREAD

**Issue by FullyWashable** [NCBI-Hackathons/Metadata_categorization#25]
I don't know if these are populated in the core, but they are empty in the actual app right now.

**Comment by eweitz** [comment]
@lepons, I won't have easy access to the `annotation` Solr core until tonight, but if I recall correctly, sample name and sample title are not populated there.  Could you populate those fields?

**Comment by lepons** [comment]
Looking at the annotation Solr core, I see that there are samples that have
sampleName and sampleTitle populated:

There are about 3420 or so samples with sampleName and maybe 114 with
sampleTitle populated, and it's consistent with what's in AnnotationsDev.
So I think the data is consistent with what was pulled from BioSample, it's
just that field is frequently missing.

[image: Inline image 1]

[image: Inline image 2]

**Comment by eweitz** [comment]
OK, thanks for the correction.  I'll update the web backend and UI to pull in those values from the Solr datastore.

**Comment by eweitz** [comment]
It turns out that sample name and sample title are already populated in the UI, as well.  As @lepons notes, only a very small fraction of records have values for these fields in the underlying Solr core.  So if this is an issue, it seems to be with the underlying BioSample data.

If on our network and tunneled into the Solr core on EC2, here's how to verify things are working as expected:

**Sample name**
- Solr query results: http://localhost:8983/solr/annotation/select?q=-sampleName%3A%220%22&wt=json&indent=true
- "numFound":3572
- Example: go to http://ec2-52-7-85-232.compute-1.amazonaws.com/queue/171 and scroll down to "RSV24HR".  Open individual record dialog, note same value in "Sample name" field

**Sample title**
- Solr query results: http://localhost:8983/solr/annotation/select?q=-sampleTitle%3A%220%22&wt=json&indent=true
- "numFound":114
- Example: go to http://ec2-52-7-85-232.compute-1.amazonaws.com/queue/257 and scroll down to "Human genome sequencing of a SCA affected individual 148".  Open individual record dialog, note same value in "Sample title" field

Given this, I'll close this ticket for now.  The underlying BioSample data issue may warrant more investigation, but that seems like a separate issue, as the data is being populated in the UI.
