### ISSUE TITLE
Add a Harvest Site field

### ISSUE THREAD

**Issue by FullyWashable** [NCBI-Hackathons/Metadata_categorization#26]
This is a field where the curators will add an anatomical location from which the cells were harvested if it is different from the anatomy of the cells (like in the case of secondary tumors or blood harvested peripheral to a body area). For SOLR, please add field; it doesn't require any population. For UI, please add to the individual record view. This is a project critical addition.

**Comment by lepons** [comment]
I created entries for this in the Solr schema for both annotation and AnnotationsDev. Since these do not contain source data, I am not planning at this time to re-index to generate the default entries. @eweitz let me know if this poses a problem for you and I can re-rerun the populations jobs, so that default values are set. But with the field in the schema, these values can be stored from user input.

**Comment by FullyWashable** [comment]
Thank you!

**Comment by eweitz** [comment]
>  @eweitz let me know if this poses a problem for you and I can re-rerun the populations jobs, so that default values are set.

@lepons, to wire this into the UI and web backend, I will need `harvestSite` pre-populated with "0" in Solr, like the other fields.  ("0" represents "empty" per our hackathon work.)  Let's hold off on that quasi-pre-population until after today's demo, which ends around 4:00 PM today.  This will be trivial to implement on my end once `harvestSite` is 0-filled.

**Comment by eweitz** [comment]
With indexers starting work tomorrow, pre-populating `harvestSite` with "0" seems like it might be time-sensitive.  If we can add `"harvestSite": "0"` for all records without wiping out existing `annot` values, then it's somewhat less urgent.  

If not, then I think we would need this part done today.  Otherwise I suspect that adding `"harvestSite": "0"` while preserving indexers' work will be complex.

**Comment by lepons** [comment]
I should be able to do this tonight. If I recall correctly, I wrote it so I
can add a new field by essentially copying the existing data, so if there
are stored annotations that aren't in the source data, I will capture them
too (I will confirm this before I run the job and run it in Dev first as a
test). Should be able to complete this easily, but can't do it until after
I put my kids to bed. I'll send around a notice when it's done. If I can't
do it tonight, I should be able to do it first thing tomorrow morning,
barring anything happening, both jobs should run in about 10 min total.
Should I restrict this to Drosophila samples or go ahead and populate
harvestSite for everything?

**Comment by eweitz** [comment]
> If I recall correctly, I wrote it so I can add a new field by essentially copying the existing data, so if there are stored annotations that aren't in the source data, I will capture them too (I will confirm this before I run the job and run it in Dev first as a test).

Fantastic!

> Should I restrict this to Drosophila samples or go ahead and populate harvestSite for everything?

Let's populate harvestSite for everything, i.e. human and Drosophila.

**Comment by lepons** [comment]
These are fully populated in annotation, I didn't fully populate them for
AnnotationsDev, which doesn't have reliable data on a number of fronts, so
I didn't think it would be useful. Let me know if you want me to run the
job for AnnotationsDev too.

**Comment by eweitz** [comment]
@FullyWashable, done.  @lepons and I have added a "Harvest Site" field to the app.  As the field is not pulling source values from BioSample, it is simply white and does not use the pink/green convention for source and annotated fields.
